version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - mongodb:/data/db
    ports:
      - "9000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - instafeed
  instafeed:
    container_name: instafeed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - instafeed
    depends_on:
      - mongodb

networks:
  instafeed:
    name: instafeed
volumes:
  mongodb: